branches:
  only:
  - "/.*/"
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: xenial
    sudo: required
language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm run build
after_success:
- ssh ubuntu@62.234.149.22 "~/frontend/vue-vehicle/build_script"
before_install:
- openssl aes-256-cbc -K $encrypted_e3a72f7a6af0_key -iv $encrypted_e3a72f7a6af0_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons: 
  ssh_known_hosts: 62.234.149.22
